---
title: "PA_measure_metrics"
author: "Tong Zhu"
date: "2024-10-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#clears the environment by removing all existing objects.
rm(list = ls())
library(PAmeasures)
library(survival)
library(rms)

```


```{r}
# Use Mayo Clinic Primary Biliary Cirrhosis Data
data(pbc)
pbc <- pbc %>% 
  filter(is.na(trt)==F) %>% 
  mutate(log_albumin = log(albumin),
         log_bili = log(bili),
         log_protime = log(protime),
         status = ifelse(status==2, 1, 0))

# Fit a full Cox PH model
fit.coxph.full <- coxph(Surv(time, status) ~ age + log_albumin + 
                          log_bili + log_protime + edema, 
                        data = pbc,x=TRUE,y=TRUE)
fit.exp <- survreg(Surv(time, status) ~ age + log_albumin +
                     log_bili + log_protime + edema,
                   data = pbc, dist="exponential", x=TRUE, y=TRUE)
fit.lognormal <- survreg(Surv(time, status) ~ age + log_albumin +
                           log_bili + log_protime + edema,
                         data = pbc, dist="lognormal", x=TRUE, y=TRUE)
fit.weibull <- survreg(Surv(time, status) ~ age + log_albumin +
                         log_bili + log_protime + edema,
                       data = pbc, dist="weibull", x=TRUE, y=TRUE)
```


```{r}
c_H <- c(pam.concordance(fit.coxph.full)$concordance,
       pam.concordance(fit.exp)$concordance,
       pam.concordance(fit.lognormal)$concordance,
       pam.concordance(fit.weibull)$concordance)
c_U <- c(pam.concordance(fit.coxph.full, timewt="n/G2")$concordance,
       pam.concordance(fit.exp, timewt="n/G2")$concordance,
       pam.concordance(fit.lognormal, timewt="n/G2")$concordance,
       pam.concordance(fit.weibull, timewt="n/G2")$concordance)
```


```{r}
r_sph <- c(pam.re(fit.coxph.full)$Re,
          pam.re(fit.exp)$Re,
          pam.re(fit.lognormal)$Re,
          pam.re(fit.weibull)$Re)

```

```{r}

train.fit.full  <- rms::cph(survival::Surv(time, status) ~ age + log_albumin + 
                          log_bili + log_protime + edema, 
                        data = pbc,x=TRUE,y=TRUE)

train.fit.exp  <- rms::cph(survival::Surv(time, status) ~ age + log_albumin + 
                          log_bili + log_protime + edema, 
                        data = pbc, dist="exponential", x=TRUE,y=TRUE)

train.fit.lognormal  <- rms::cph(survival::Surv(time, status) ~ age + log_albumin + 
                          log_bili + log_protime + edema, 
                        data = pbc, dist="lognormal", x=TRUE,y=TRUE)

train.fit.weibull  <- rms::cph(survival::Surv(time, status) ~ age + log_albumin + 
                          log_bili + log_protime + edema, 
                        data = pbc, dist="weibull", x=TRUE,y=TRUE)


r_sh <- c(pam.schemper(train.fit.full, pbc, pbc)$Dx,
        pam.schemper(train.fit.exp, pbc, pbc)$Dx,
        pam.schemper(train.fit.lognormal, pbc, pbc)$Dx,
        pam.schemper(train.fit.weibull, pbc, pbc)$Dx)
```


```{r}
taulist <- seq(0, max(pbc$time), 300)
median_time <- median(pbc$time)
brier_score <- c(
  pam.Brier(fit.coxph.full, pbc, median_time),
  pam.Brier(fit.exp, pbc, median_time),
  pam.Brier(fit.lognormal, pbc, median_time),
  pam.Brier(fit.weibull, pbc, median_time)
)
```


```{r}
time_dep_auc_full <- pam.survivalROC(Stime = pbc$time,
            status = pbc$status,
            marker = predict(fit.coxph.full, newdata=pbc, type = "lp") ,
            predict.time = quantile(pbc$time, 0.5), 
            method="KM")$AUC
time_dep_auc_exp <- pam.survivalROC(Stime = pbc$time,
            status = pbc$status,
            marker = - predict(fit.exp, newdata=pbc, type = "lp") ,
            predict.time = quantile(pbc$time, 0.5), 
            method="KM")$AUC
time_dep_auc_log <- pam.survivalROC(Stime = pbc$time,
            status = pbc$status,
            marker = - predict(fit.lognormal, newdata=pbc, type = "lp") ,
            predict.time = quantile(pbc$time, 0.5), 
            method="KM")$AUC
time_dep_auc_weibull <- pam.survivalROC(Stime = pbc$time,
            status = pbc$status,
            marker = - predict(fit.weibull, newdata=pbc, type = "lp") ,
            predict.time = quantile(pbc$time, 0.5), 
            method="KM")$AUC

time_dep_auc <- c(
  time_dep_auc_full,
  time_dep_auc_exp,
  time_dep_auc_log,
  time_dep_auc_weibull
)
```

```{r}
coxph.out <- pam.coxph(fit.coxph.full)%>% 
  Reduce("c",.) %>% as.numeric()
exp.out <- pam.survreg(fit.exp)%>% 
  Reduce("c",.) %>% as.numeric()
lognormal.out <- pam.survreg(fit.lognormal)%>% 
  Reduce("c",.) %>% as.numeric()
weibull.out <- pam.survreg(fit.weibull)%>% 
  Reduce("c",.) %>% as.numeric()
```

```{r}
tabel_df <- cbind(coxph.out, exp.out, lognormal.out, weibull.out) %>%
  rbind(c_H, c_U) %>%
  rbind(r_sph) %>% 
  rbind(r_sh) %>%
  rbind(brier_score) %>% 
  rbind(time_dep_auc) %>%
  as.data.frame() %>% round(2)
row.names(tabel_df) <- c("R.squared", "L.squared", 
                        "Harrell’s C", "Uno’s C", "R_sph", "R_sh", "Brier Score", "Time-dep AUC")
tabel_df
```


